### ISSUE TITLE
strange SAXParseExceptions in round configuration

### ISSUE THREAD

**Issue by alee** [virtualcommons/foraging#14]
Super annoying bug related to the new FMRI config parameterization. Will reliably generate SAXParseExceptions whenever the <entry key="repeating">25</entry> line is changed in source control. Changing it locally gets rid of the exception, but once it's committed it starts up again. 

```
     [copy] Copying 150 files to /home/alllee/workspace/foraging/target/classes/conf                                                                                                                                                                                      [22/1833]
     [java] java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
     [java]     at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
     [java]     at java.util.Properties$XmlSupport.load(Properties.java:1201)
     [java]     at java.util.Properties.loadFromXML(Properties.java:881)
     [java]     at edu.asu.commons.conf.PropertiesConfiguration.loadProperties(PropertiesConfiguration.java:55)
     [java]     at edu.asu.commons.conf.ExperimentRoundParameters$Base.<init>(ExperimentRoundParameters.java:71)
     [java]     at edu.asu.commons.foraging.conf.RoundConfiguration.<init>(RoundConfiguration.java:146)
     [java]     at edu.asu.commons.foraging.conf.ServerConfiguration.createRoundConfiguration(ServerConfiguration.java:49)
     [java]     at edu.asu.commons.foraging.conf.ServerConfiguration.createRoundConfiguration(ServerConfiguration.java:28)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.loadParameters(ExperimentConfiguration.java:181)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.loadServerProperties(ExperimentConfiguration.java:170)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.<init>(ExperimentConfiguration.java:150)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.<init>(ExperimentConfiguration.java:137)
     [java]     at edu.asu.commons.foraging.conf.ServerConfiguration.<init>(ServerConfiguration.java:40)
     [java]     at edu.asu.commons.foraging.server.ForagingServer.<init>(ForagingServer.java:135)
     [java]     at edu.asu.commons.foraging.server.ForagingServer.main(ForagingServer.java:1181)
     [java] Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
     [java]     at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
     [java]     at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
     [java]     at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
     [java]     at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
     [java]     at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
     [java]     at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
     [java]     at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
     [java]     at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
     [java]     at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
     [java]     ... 14 more
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Couldn't loadFromXML using resource: conf/ and stream: java.io.ByteArrayInputStream@a09ee92
     [java]     at edu.asu.commons.conf.PropertiesConfiguration.loadProperties(PropertiesConfiguration.java:58)
     [java]     at edu.asu.commons.conf.ExperimentRoundParameters$Base.<init>(ExperimentRoundParameters.java:71)
     [java]     at edu.asu.commons.foraging.conf.RoundConfiguration.<init>(RoundConfiguration.java:146)
     [java]     at edu.asu.commons.foraging.conf.ServerConfiguration.createRoundConfiguration(ServerConfiguration.java:49)
     [java]     at edu.asu.commons.foraging.conf.ServerConfiguration.createRoundConfiguration(ServerConfiguration.java:28)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.loadParameters(ExperimentConfiguration.java:181)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.loadServerProperties(ExperimentConfiguration.java:170)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.<init>(ExperimentConfiguration.java:150)
     [java]     at edu.asu.commons.conf.ExperimentConfiguration$Base.<init>(ExperimentConfiguration.java:137)
     [java]     at edu.asu.commons.foraging.conf.ServerConfiguration.<init>(ServerConfiguration.java:40)
     [java]     at edu.asu.commons.foraging.server.ForagingServer.<init>(ForagingServer.java:135)
     [java]     at edu.asu.commons.foraging.server.ForagingServer.main(ForagingServer.java:1181)
     [java] Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
     [java]     at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
     [java]     at java.util.Properties$XmlSupport.load(Properties.java:1201)
     [java]     at java.util.Properties.loadFromXML(Properties.java:881)
     [java]     at edu.asu.commons.conf.PropertiesConfiguration.loadProperties(PropertiesConfiguration.java:55)
     [java]     ... 11 more
     [java] Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
     [java]     at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
     [java]     at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
     [java]     at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
     [java]     at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
     [java]     at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
     [java]     at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
     [java]     at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
     [java]     at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
     [java]     at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
     [java]     ... 14 more

```

**Comment by alee** [comment]
Fixed in virtualcommons/sesef@2fb2d813a2d99c515c02f16a452410ad7ad7295d
