### ISSUE TITLE
Java 8 webstart issues

### ISSUE THREAD

**Issue by alee** [virtualcommons/foraging#6]
Java 8 clients appear to make a separate initial request that generates an invalid stream header exception on initial socket connect - need to investigate and fix. Killing the server and restarting it pops up a notification on the client saying "Do you want to connect to x.x.x.x?". At that point if you click OK on the client, it will connect normally to the server.

```
Mar 21, 2015 1:09:15 PM edu.asu.commons.net.ServerSocketDispatcher processIncomingConnections
INFO: incoming connection: Socket[addr=/72.201.66.20,port=49539,localport=16001]
java.io.StreamCorruptedException: invalid stream header: 47455420
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
        at edu.asu.commons.net.SocketDispatcherWorker.<init>(SocketDispatcherWorker.java:38)
        at edu.asu.commons.net.SocketDispatcherWorker.<init>(SocketDispatcherWorker.java:42)
        at edu.asu.commons.net.ServerSocketDispatcher.processIncomingConnections(ServerSocketDispatcher.java:91)
        at edu.asu.commons.net.AbstractServerDispatcher$2.run(AbstractServerDispatcher.java:118)
Mar 21, 2015 1:09:15 PM edu.asu.commons.net.AbstractServerDispatcher$2 run
SEVERE: IO Exception while processing incoming connections: java.io.StreamCorruptedException: invalid stream header: 47455420
```

**Comment by alee** [comment]
fixed by signing jars
